### ISSUE TITLE
epic: Connector: Spark: Support more file formats on Hadoop

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#1718]
As of Q3, Quasar can generate (RDD) Spark query plans and run inside a Hadoop environment on ordinary JSON text files. However, the core Spark connector needs to be improved in numerous ways, including:

* **Performance Improvements**. For example, avoiding JSON as an intermediate and going directly from source format into EJSON.
* **Supported File Formats**. At minimum, common file formats should be supported, including Parquet, Avro, Orc, EJSON.

- [ ]  Support CSV files
- [ ]  Support Hive tables
- [ ]  Support anything with a SerDe
- [ ]  Support ORC
- [ ]  Support Avro
- [ ]  Support XML files
- [ ]  Support EJSON files

**Comment by paulp** [comment]
It would be great if [this glue](https://github.com/quasar-analytics/quasar/blob/master/marklogic/src/main/scala/quasar/physical/marklogic/ejson/jsonParser.scala) could be moved somewhere less specific to marklogic.

**Comment by wemrysi** [comment]
@paulp It absolutely should be, probably to `ejson`.

**Comment by wemrysi** [comment]
@paulp See #1721

**Comment by jdegoes** [comment]
@rabbitonweb Please open up a ticket for Parquet so we can track that separately.
