### ISSUE TITLE
Support all of EJson.

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1814]
- [ ] Replace Data with EJson in LogicalPlan’s `Constant`. (#1807)
- [ ] Coproduct SQL² with EJson rather than using the SQL² data components (#1808)
- [ ] Add support for Metadata (etc.?) to SQL² parser (#1809)
- [ ] eliminate Data from connectors and/or encode all of EJson properly (#1810, #1811, #1812)
- [ ] return results as EJson rather than Data (#1813)

Addtional useful, but not critical steps:
- replace SQL² parser with invertible-syntax that operates on the individual SQL and EJson functors (which compose with syntax for Coproduct and fixed-point operators).
- Coproduct LogicalPlan with EJson rather than using `Constant`
