### ISSUE TITLE
epic: Connector: MarkLogic Overhaul

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#1999]
# Usability

The connector should require no manual setup process before it's fully usable.

 - [ ] TDB: List issues here.

# Generate Optimal XQuery

Generated XQuery should be compact and algorithmically efficient.

 - [ ] TBD: List issues here.

# Index Enhancements

Predicates on indexed data should leverage those indices to the maximum extent possible.

 - [ ] TBD: List issues here.

# Aggregations Enhancements

Standard aggregations should utilize MarkLogic's own facilities for aggregation.

 - [ ] TBD: List issues here.

# Optic API Enhancements

The Optic API should be utilized whenever possible.

 - [ ] TBD: List issues here.

# Schema Enhancements

Statistical structural typing should leverage existing schema information when known.

 - [ ] TBD: List issues here.

# Miscellaneous

Other issues currently created can be categorized here.

 - [ ] TBD: List issues here.

**Comment by jdegoes** [comment]
@zeeiyerWork This needs additional specification. I'm sure @wemrysi can help fill out and we can do some independent investigation on whatever remains.
