### ISSUE TITLE
epic: Connector: Couchbase Overhaul

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#2000]
# Joins

 - [ ] Support equi-joins on calculated fields
 - [ ] Support non-equi inner joins via cross / filter
 - [ ] Support non-equi outer joins

# N1QL Generation

Generate efficient and compact N1QL.

 - [ ] TBD: List issues here

# Analytics Service

Transparently generate SQL++ for the analytics service when present.

 - [ ] TBD: List issues here.

# Text Search

Support Couchbase's text search facilities for any predicates on string fields.

 - [ ] TBD: List issues here.

# Miscellaneous

For outstanding issues not covered above.

 - [ ] TBD: List issues here

**Comment by jdegoes** [comment]
@zeeiyerWork Same for this one, @drostron can help fill in some detail.
