### ISSUE TITLE
epic: Connector: Spark Overhaul

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#2002]
- [ ] Implement direct codecs that eliminate intermediate transforms
 - [ ] Do not compile to Spark ops that result in a chokepoint
 - [ ] Support data frames for regular data
 - [ ] TBD

# File Formats (covered in #1718)

 - [ ] Support CSV files
 - [ ] Support Hive tables
 - [ ] Support anything with a SerDe
 - [ ] Support ORC
 - [ ] Support Avro
 - [ ] Support XML files
 - [ ] Support EJSON files

# Miscellaneous

Whatever else doesn't fit into the above categories.

**Comment by jdegoes** [comment]
@zeeiyerWork Same here, @rabbitonweb can help flesh this out a bit based on known limitations & possible improvements.

**Comment by rabbitonweb** [comment]
will do
