### ISSUE TITLE
epic: SQL2 & QScript: Phase B: Completion

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#2020]
# SQL<sup>2</sup>

Issues targeted at completing support for SQL<sup>2</sup>.

 - [ ] Pattern matching syntax
 - [ ] Pattern matching compilation to QScript
 - [ ] TBD: List of remaining issues

# QScript Compiler Performance

Issues targeted at reducing compiler time on large queries to tens of milliseconds, rather than hundreds of milliseconds or seconds.

 - [ ] Support variables in QScript that can be pushed into connectors so parameterized queries only need to be compiled once
 - [ ] TBD: List of remaining issues

# QScript Expressiveness

Issues targeted at increasing the expressiveness of QScript to allow more efficient plans to more easily be generated by connectors; and to allow expressing features not yet possible, as might be required by pattern matching and other features of SQL<sup>2</sup>.

 - [ ] TBD: List of remaining issues

**Comment by jdegoes** [comment]
@zeeiyerWork Both @alissapajer and @sellout need consulting here, and benchmarking will inform various issues. The goal should be to flesh this EPIC out until it reaches a degree of detail that gives us confidence QScript / SQL<sup>2</sup> will be "done" when all issues have been completed.
