### ISSUE TITLE
epic: Preparation for Quasar Clustering

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#2176]
As preparation for Quasar Clustering, an extensive re-architecturing is required that removes the single-node assumptions currently made around the metastore persistence layer.

This EPIC is to track all of the many tasks that need to be performed to remove the single-node assumption, so that multiple Quasar nodes may simultaneously interact with a centralized PostgreSQL metastore without race conditions, clobbering, or permanent inconsistency.

It seems that we would need at least the following (WIP): 
- [ ] Ensure that server-side config elements are shareable across JVMs (e.g. the Metastore) instead of local file-system.
- [ ] Ensure correct multi-threaded semantics across JVMs to avoid clobbering.
- [ ] Application level load-balancer that can intelligently route REST calls to Quasar-JVMS (based on Round-robin, Least busy and numerous other possible algorithms).
- [ ] Application level heart-beat, so non-responsive Quasar JVMs are automatically taken out of the cluster and join back upon regaining health.

**Comment by jdegoes** [comment]
@zeeiyerWork This needs specs & subtasks.
