### ISSUE TITLE
epic: Improve Error Messaging on the Backend.

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2603]
This EPIC is in keeping with backend engineer's desire to have more business facing epics which then include a smorgasbord of issues across various TOPICS to deliver the business objective as against epics that deal with the logical composition of the implementation.

Current Error messaging is often too cryptic, not understandable, not actionable and does not provide enough context. Result is that:

1. Front-end is not able to transcribe/translate and provide understandable/actionable error messaging to the end-user, resulting in confusion and on occasion abandonment by the end-user.
2. It should also be noted that at times, the front-end simply relays what the backend provides as an error-message. Therefore, backend implementation should note that some of the messaging they return is for end-user eyes.

This epic is a container for all:
- [ ] All issues  needed on the backend, to provide more meaningful/actionable error messages to the front-end. 
- [ ] Consolidating Error Message JSONs presented to the front-end, so there is only 1 type of JSON to parse, in the case of either a single error message or an Array of messages.
- [ ] There is also a desire to include a "categorization" enumeration in the JSON returned, so some context can be preserved in the messaging to the end-user.
